locale: "en-US"
site_theme: "default"

title: "Kun Hu | 胡琨"
title_separator: "-"
name: &name "Kun Hu"
description: &description "Robust SLAM and multi-sensor fusion for coal mine robots"
url: https://kj-falloutlast.github.io
baseurl: ""
repository: "KJ-Falloutlast/KJ-Falloutlast.github.io"

author:
  avatar: "profile.png"
  name: "Kun Hu | 胡琨"
  bio: "Master student at CoalMine Robot Lab, China University of Mining and Technology. Research interests: Multisensor Fusion SLAM, Spatial AI, and Visual Language Action"
  location: "Xuzhou, China"
  employer: "China University of Mining and Technology"
  email: "falloutlast888@gmail.com"
  googlescholar: "https://scholar.google.com.hk/citations?user=j_ZdCsAAAAAJ&hl=zh-CN"
  orcid: "https://orcid.org/0009-0006-9926-2941"
  github: "KJ-Falloutlast"
  # linkedin: "你的 LinkedIn 用户名"
  linkedin: "https://www.linkedin.com/in/kun-hu-175b34356/"

publication_category:
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"
  patents:
    title: "Patents"
